# Generated by Django 3.0 on 2020-10-01 04:51

import apps.perfil.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default-user-image.jpg', upload_to='profile_pics')),
                ('aboutus', models.TextField(default='Sobre nosotros...')),
                ('instagram', models.CharField(default='Instagram...', max_length=30)),
                ('twitter', models.CharField(default='@Twitter...', max_length=30)),
                ('telefono', models.BigIntegerField(default=0)),
                ('rubro', models.IntegerField(choices=[(1, 'OTROS'), (2, 'INDUMENTARIA'), (3, 'CERVECERIA'), (4, 'COSMETICO'), (5, 'SERVICIOS')], default=apps.perfil.models.Rubro['OTROS'])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
