# Generated by Django 3.0 on 2020-09-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-user-image.jpg', upload_to='profile_pics'),
        ),
    ]
