# Generated by Django 3.0 on 2020-09-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_profile_rubro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rubro',
            field=models.CharField(choices=[('CARPINTERO', 'Carpintero'), ('HERRERO', 'Herrero'), ('OTROS', 'Otros')], default='OTROS', max_length=30),
        ),
    ]
