# Generated by Django 3.0 on 2020-09-30 13:56

import apps.perfil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_auto_20200929_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rubro',
            field=models.IntegerField(choices=[(1, 'OTROS'), (2, 'INDUMENTARIA'), (3, 'CERVECERIA'), (4, 'COSMETICO'), (5, 'SERVICIOS')], default=apps.perfil.models.Rubro['OTROS']),
        ),
    ]
