# Generated by Django 3.0 on 2020-09-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aboutus',
            field=models.TextField(default='Sobre nosotros...'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.TextField(default='Instagram...'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.TextField(default='Twitter...'),
        ),
    ]
