# Generated by Django 3.0 on 2020-10-01 17:16

import apps.perfil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20201001_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, default='Instagram...', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rubro',
            field=models.IntegerField(choices=[(1, 'OTROS'), (2, 'INDUMENTARIA'), (3, 'CERVECERIA'), (4, 'COSMETICO'), (5, 'SERVICIOS'), (6, 'ALIMENTOS'), (7, 'INFORMATICO'), (8, 'ARTESANIAS'), (9, 'HERRERIA'), (10, 'VAPE'), (11, 'VEHICULOS')], default=apps.perfil.models.Rubro['OTROS']),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, default='@Twitter...', max_length=30),
        ),
    ]
