# Generated by Django 3.0 on 2020-09-25 14:11

from django.conf import settings
import django.contrib.auth.mixins
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.edit


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('productos', '0002_auto_20200925_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crear',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, django.views.generic.edit.CreateView, 'usuarios.usuario'),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
